name: Deploy to cPanel

on:
  push:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to cPanel
      env:
        HOST: cp02.zagrio.com/cpanel
        USERNAME: muchshop
        PASSWORD: NP9:kkuWeY23(6
      run: |
        scp -r . $USERNAME@$HOST:/path/to/your/cpanel/directory
